site_name: My Docs
theme:
  name: material
  nav_style: dark
  features:
    - content.code.copy
    - content.code.select
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
nav:
  - 'index.md'
  - 'certificate.md'
  - 'chocolatey.md'
  - 'git.md'
  - 'isilon.md'
  - 'linux.md'
  - 'mkdocs.md'  
  - 'openssl.md'
  - 'openssh.md'
  - 'powershell.md'
  - 'about.md'
  
not_in_nav:  
  /private.md
# use_directory_urls: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
